// <auto-generated />
using System;
using DataProcessingCenter.Tests.TestDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataProcessingCenter.Tests.Migrations
{
    [DbContext(typeof(MyIndexDbContext))]
    partial class MyIndexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataProcessingCenter.IndexDB.IndexDBs", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountAddress");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("TransationHash");

                    b.HasKey("ID");

                    b.ToTable("indexs");
                });
#pragma warning restore 612, 618
        }
    }
}
