// <auto-generated />
using System;
using EthImgStorage_Web_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EthImgStorage_Web_API.Migrations
{
    [DbContext(typeof(IndexDbContext))]
    [Migration("20181207022000_changeModel")]
    partial class changeModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataProcessingCenter.IndexDB.IndexDBs", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountAddress");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("TransationHash");

                    b.HasKey("ID");

                    b.ToTable("indexs");
                });
#pragma warning restore 612, 618
        }
    }
}
