// <auto-generated />
using System;
using EthImgStorage_Web_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EthImgStorage_Web_API.Migrations
{
    [DbContext(typeof(IndexDbContext))]
    partial class IndexDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EthImgStorage_Web_API.Models.IndexDB", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountAddress");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name");

                    b.Property<string>("TransationHash");

                    b.HasKey("ID");

                    b.ToTable("Indexs");
                });
#pragma warning restore 612, 618
        }
    }
}
